apiVersion: v1
kind: Service
metadata:
  name: php-and-nginx-service
spec:
  type: LoadBalancer
  selector:
    component: php-and-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
