imports:
    - { resource: config.yml }

framework:
    php_errors:
        log: true
        throw: false
    assets:
        json_manifest_path: "%kernel.project_dir%/web/build/manifest.json"
    # https://symfony.com/doc/current/cache.html#configuring-cache-with-frameworkbundle
    # https://github.com/symfony/demo/blob/master/config/packages/prod/doctrine.yaml
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
#    validation:
#        cache: validator.mapping.cache.doctrine.apc
#    serializer:
#        cache: serializer.mapping.cache.doctrine.apc


parameters:
    router.request_context.scheme: 'https'

# https://github.com/doctrine/DoctrineBundle/releases/tag/2.0.1
# https://symfony.com/blog/new-in-doctrinebundle-1-11-0
# https://github.com/symfony/demo/blob/master/config/packages/prod/doctrine.yaml
doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            formatter: monolog.formatter.json
            max_files: 7
            channels: ["!api", "!stripe", "!loopeat"]
        api:
            type: rotating_file
            path: "%kernel.logs_dir%/api.%kernel.environment%.log"
            level: info
            formatter: monolog.formatter.json
            max_files: 7
            channels: [api]
        messenger:
            type: rotating_file
            path: "%kernel.logs_dir%/messenger.%kernel.environment%.log"
            level: debug
            formatter: monolog.formatter.json
            max_files: 7
            channels: [messenger]
        fee_calculation:
            type: rotating_file
            path: "%kernel.logs_dir%/fee_calculation.%kernel.environment%.log"
            level: info
            formatter: monolog.formatter.json
            max_files: 7
            channels: [fee_calculation]
        timing:
            type: rotating_file
            path: "%kernel.logs_dir%/timing.%kernel.environment%.log"
            level: info
            max_files: 7
            channels: [timing]
        geofencing:
            type: rotating_file
            path: "%kernel.logs_dir%/geofencing.%kernel.environment%.log"
            level: info
            formatter: monolog.formatter.json
            max_files: 7
            channels: [geofencing]
        stripe:
            type: rotating_file
            path: "%kernel.logs_dir%/stripe.%kernel.environment%.log"
            level: info
            max_files: 7
            channels: [stripe]
        loopeat:
            type: rotating_file
            path: "%kernel.logs_dir%/loopeat.%kernel.environment%.log"
            level: info
            max_files: 7
            channels: [loopeat]
        mailer:
            level:    error
            type:     rotating_file
            path:     '%kernel.logs_dir%/mailer.%kernel.environment%.log'
            max_files: 7
            channels: [mailer]
        console:
            type:  console

fos_user:
    registration:
        confirmation:
            enabled: true

sentry:
    dsn: '%sentry_public_dsn%'
    options:
        # https://github.com/getsentry/sentry-symfony#step-3-configure-the-sdk
        # https://docs.sentry.io/platforms/php/#php-specific-options
        excluded_exceptions:
            - Symfony\Component\Security\Core\Exception\AccessDeniedException
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
            - ApiPlatform\Core\Bridge\Symfony\Validator\Exception\ValidationException

# see
# https://github.com/liip/LiipImagineBundle/issues/1018
# https://github.com/liip/LiipImagineBundle/issues/1144
# liip_imagine:
#     resolvers:
#         default:
#             web_path:
#                 web_root: '%kernel.project_dir%/../../shared/web'
#     loaders:
#         default:
#             filesystem:
#                 data_root:
#                     - '%kernel.project_dir%/../../shared/web'
#                     - '%kernel.project_dir%/web'
